### PR TITLE
Modified keys in ruby armour recipes to map correctly

### PR DESCRIPTION
**Pull request by samyrataylor**
Hi,

Thanks for this mod, I'm really enjoying it.

I was having an issue with the ruby armour where it was uncraftable in both the 20w16a and 20w17a versions, the logs indicated that the issue was in the recipe files, it looks like the keys just didn't match the crafting recipe. 

Thanks

### CODE REVIEW

**Comment by kwpugh** [comment]
Hey, sorry about, mistake from moving too fast.  updated will be pushed shortly.

What do you think about a set of obsidian tools and armor being added to this mod?

**Comment by samyrataylor** [comment]
No worries, I've done the same thing way too many times. 
That's a great idea! What are you thinking in terms of strength in relation to the other materials?

**Comment by kwpugh** [comment]
maybe place obsidian gear above steel, but less than emerald

**Comment by kwpugh** [comment]
I made the recipe mistake in 1.15.2 as well, updating.  Thanks for letting me know.

**Comment by kwpugh** [comment]
Both version now updated.

**Comment by samyrataylor** [comment]
Yeah I think that would make the most sense, obviously the blocks are hard but getting them is definitely easier than emerald, and okay great, thanks again for the mod and quick response!

**Comment by kwpugh** [comment]
manually changed

**Pull request closed without merging**
